# Auto-generated by rylai. Do not edit manually.

from __future__ import annotations

import sys

from ._typing import KwargsItems

if sys.version_info < (3, 11):
    from typing_extensions import Unpack
else:
    from typing import Unpack

__all__ = [
    "show_kwargs",
    "multiply",
]

def show_kwargs(**kwargs: Unpack[KwargsItems]) -> None:
    """Example of using "add_content" and "override" in rylai.toml to show the types of kwargs."""

def multiply(a: float, b: float) -> float:
    """
    Multiply two values.
    Demonstrates overriding individual parameter types and return type.
    """
