# Auto-generated by rylai. Do not edit manually.

from __future__ import annotations

import sys
import typing as t

from ._typing import KwargsItems

if sys.version_info < (3, 11):
    from typing_extensions import Unpack
else:
    from typing import Unpack

__all__ = [
    "show_kwargs",
    "apply_policy",
]

def show_kwargs(**kwargs: Unpack[KwargsItems]) -> None:
    """Example of using "add_content" and "override" in rylai.toml to show the types of kwargs."""

def apply_policy(
    mode: t.Literal["accept", "deny", "auto"],
) -> dict[str, t.Literal["accept", "deny", "auto"]]:
    """
    Apply a decision policy to predefined items.
    Demonstrates overriding parameter and return types for richer Python type hints.
    """
