# Auto-generated by rylai. Do not edit manually.

from __future__ import annotations

import typing as t

__all__ = [
    "AsyncWorker",
    "sleep",
    "cancellable",
]

@t.final
class AsyncWorker:
    """A `#[pyclass]` exposing async methods."""
    @property
    def factor(self) -> float: ...
    def __init__(self, factor: float) -> None:
        """`#[new]` stays synchronous: `def __init__(self, factor: float) -> None`."""

    async def scale(self, n: int) -> float:
        """Async instance method -> `async def scale(self, n: int) -> float`."""

    @staticmethod
    async def unit() -> AsyncWorker:
        """Async staticmethod -> `async def unit() -> AsyncWorker` (under `@staticmethod`)."""

async def sleep(seconds: float, value: int) -> int:
    """
    Sleep for the given number of seconds, then return the value unchanged.

    Mirrors the pyo3 async-await guide: an `async fn` decorated with `#[pyfunction]` exposes a
    coroutine to Python, so the stub renders `async def sleep(seconds: float, value: int) -> int`.
    """

async def cancellable() -> None:
    """
    A cancellable coroutine.

    `#[pyo3(cancel_handle)]` injects a [`CancelHandle`] that the Rust body polls to cooperate
    with Python-side cancellation. It is NOT a Python-visible parameter, so Rylai drops it from
    the stub and the result is `async def cancellable() -> None:`.
    """
