# Auto-generated by rylai. Do not edit manually.

from __future__ import annotations

from pyo3_sample.bb import B

class A:
    def __init__(self) -> None:
        ...

    def make_b(self) -> B:
        """Returns a `B` from `pyo3_sample.bb` (Rylai emits `from pyo3_sample.bb import B` in `aa` stub)."""


