# Auto-generated by rylai. Do not edit manually.

"""
This example shows how to use add_content in rylai.toml.
You can add content after the auto-generated banner.
"""

from __future__ import annotations

import typing as t

from pyo3_sample.bb import B

__all__ = [
    "A",
]

@t.final
class A:
    def __init__(self) -> None: ...
    def make_b(self) -> B:
        """Returns a `B` from `pyo3_sample.bb` (Rylai emits `from pyo3_sample.bb import B` in `aa` stub)."""
