# Auto-generated by rylai. Do not edit manually.

from __future__ import annotations

# Module: pyo3_sample
def sum_as_string(a: int, b: int) -> str:
    """Formats the sum of two numbers as string."""

def add(a: int, b: int) -> int:
    """Renamed via #[pyo3(name = "...")]"""

class C:
    def __init__(self) -> None:
        ...


