# Auto-generated by rylai. Do not edit manually.

"""
This example shows how to use add_content in rylai.toml.
You can add content after the auto-generated banner.
"""

# ruff: noqa: F401
from __future__ import annotations

import typing as t

from cross_module_sample.bb import B

__all__ = [
    "A",
]

@t.final
class A:
    def __init__(self) -> None: ...
    def make_b(self) -> B:
        """Returns a `B` from `cross_module_sample.bb` (Rylai emits `from cross_module_sample.bb import B` in `aa` stub)."""
