format = [
    "uvx ruff format",
    "uvx ruff check --select I --fix",
    "uvx ruff check --select F401 --fix",
]

[[add_content]]
file = "override_sample.pyi"
location = "after-import-typing"
content = '''
from ._typing import KwargsItems
import sys
if sys.version_info < (3, 11):
    from typing_extensions import Unpack
else:
    from typing import Unpack
'''

[[override]]
item = "override_sample::show_kwargs"
stub = "def show_kwargs(**kwargs: Unpack[KwargsItems]) -> None:"

[[override]]
item = "override_sample::multiply"
param_types = { a = "float", b = "float" }
return_type = "float"
