# Auto-generated by rylai. Do not edit manually.

from __future__ import annotations


__all__ = [
    "distance",
]

def distance(x1: float, y1: float, x2: float, y2: float) -> float:
    """Calculate the Euclidean distance between two 2D points."""

# Extended with add_content: see extra_types.pyi for the Point type alias.
