# Auto-generated by rylai. Do not edit manually.

from __future__ import annotations

import typing as t

__all__ = [
    "WithInit",
]

@t.final
class WithInit:
    """A class that carries both `#[new]` and an explicit `fn __init__` (PyO3 initializer mode)."""
    def __new__(cls, value: int) -> WithInit: ...
    def __init__(self, value: int) -> None: ...
