use anyhow::Result;
use serde::Deserialize;
use std::collections::HashMap;
use std::path::Path;

#[derive(Debug, Default, Deserialize)]
pub struct Config {
    /// Extra Rust type → Python type overrides (e.g. "numpy::PyReadonlyArray1" = "numpy.ndarray")
    #[serde(default)]
    pub type_map: HashMap<String, String>,

    #[serde(default)]
    #[allow(dead_code)] // Phase 5: cfg(feature) gating
    pub features: FeaturesConfig,

    #[serde(default)]
    pub fallback: FallbackConfig,

    #[serde(default)]
    pub output: OutputConfig,

    /// Manual stub overrides for specific items
    #[serde(default, rename = "override")]
    pub overrides: Vec<OverrideEntry>,
}

#[derive(Debug, Default, Deserialize)]
pub struct FeaturesConfig {
    /// cfg features considered active during parsing (Phase 5)
    #[serde(default)]
    #[allow(dead_code)]
    pub enabled: Vec<String>,
}

#[derive(Debug, Deserialize)]
pub struct FallbackConfig {
    /// What to do when a type cannot be inferred statically:
    /// "any" (default) | "error" | "skip"
    #[serde(default = "default_fallback_strategy")]
    pub strategy: FallbackStrategy,
}

impl Default for FallbackConfig {
    fn default() -> Self {
        Self {
            strategy: FallbackStrategy::Any,
        }
    }
}

#[derive(Debug, Default, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum FallbackStrategy {
    /// Emit `Any` and print a warning (default)
    #[default]
    Any,
    /// Hard error — stop generation and report the unknown type
    Error,
    /// Silently skip items with unresolvable types
    Skip,
}

fn default_fallback_strategy() -> FallbackStrategy {
    FallbackStrategy::Any
}

#[derive(Debug, Deserialize)]
pub struct OutputConfig {
    /// Python version string, affects Optional[T] vs T | None syntax
    #[serde(default = "default_python_version")]
    pub python_version: String,

    /// Prepend "# Auto-generated by rylai-stub-gen" header
    #[serde(default = "default_true")]
    pub add_header: bool,
}

impl Default for OutputConfig {
    fn default() -> Self {
        Self {
            python_version: default_python_version(),
            add_header: true,
        }
    }
}

fn default_python_version() -> String {
    "3.10".to_string()
}

fn default_true() -> bool {
    true
}

#[derive(Debug, Deserialize)]
pub struct OverrideEntry {
    /// Fully-qualified item path, e.g. "my_module::complex_function"
    pub item: String,
    /// Raw Python stub line, e.g. "def complex_function(x: Any, **kwargs: Any) -> dict[str, Any]: ..."
    pub stub: String,
}

impl Config {
    /// Load from file if it exists; return default config if the file is absent.
    pub fn load_or_default(path: &Path) -> Result<Self> {
        if !path.exists() {
            return Ok(Self::default());
        }
        let content = std::fs::read_to_string(path)?;
        let config: Self = toml::from_str(&content)?;
        Ok(config)
    }

    /// Return the Python version as (major, minor) tuple for comparison.
    pub fn python_version_tuple(&self) -> (u32, u32) {
        let parts: Vec<u32> = self
            .output
            .python_version
            .split('.')
            .filter_map(|s| s.parse().ok())
            .collect();
        (
            parts.first().copied().unwrap_or(3),
            parts.get(1).copied().unwrap_or(10),
        )
    }

    /// Whether to use `X | None` (py ≥ 3.10) or `Optional[X]`.
    pub fn use_union_syntax(&self) -> bool {
        self.python_version_tuple() >= (3, 10)
    }
}
