use anyhow::Result;
use serde::Deserialize;
use std::collections::HashMap;
use std::path::Path;

#[derive(Debug, Default, Deserialize)]
pub struct Config {
    /// Extra Rust type → Python type overrides (e.g. "numpy::PyReadonlyArray1" = "numpy.ndarray")
    #[serde(default)]
    pub type_map: HashMap<String, String>,

    #[serde(default)]
    pub features: FeaturesConfig,

    #[serde(default)]
    pub fallback: FallbackConfig,

    #[serde(default)]
    pub output: OutputConfig,

    /// Manual stub overrides for specific items
    #[serde(default, rename = "override")]
    pub overrides: Vec<OverrideEntry>,
}

#[derive(Debug, Default, Deserialize)]
pub struct FeaturesConfig {
    /// cfg features considered active during parsing (used to evaluate #[cfg(feature = "...")]).
    #[serde(default)]
    pub enabled: Vec<String>,
}

#[derive(Debug, Deserialize)]
pub struct FallbackConfig {
    /// What to do when a type cannot be inferred statically:
    /// "any" (default) | "error" | "skip"
    #[serde(default = "default_fallback_strategy")]
    pub strategy: FallbackStrategy,
}

impl Default for FallbackConfig {
    fn default() -> Self {
        Self {
            strategy: FallbackStrategy::Any,
        }
    }
}

#[derive(Debug, Default, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum FallbackStrategy {
    /// Emit `Any` and print a warning (default)
    #[default]
    Any,
    /// Hard error — stop generation and report the unknown type
    Error,
    /// Silently skip items with unresolvable types
    Skip,
}

fn default_fallback_strategy() -> FallbackStrategy {
    FallbackStrategy::Any
}

#[derive(Debug, Deserialize)]
pub struct OutputConfig {
    /// Python version string, affects Optional[T] vs T | None syntax
    #[serde(default = "default_python_version")]
    pub python_version: String,

    /// Prepend "# Auto-generated by rylai" header
    #[serde(default = "default_true")]
    pub add_header: bool,
}

impl Default for OutputConfig {
    fn default() -> Self {
        Self {
            python_version: default_python_version(),
            add_header: true,
        }
    }
}

fn default_python_version() -> String {
    "3.10".to_string()
}

fn default_true() -> bool {
    true
}

#[derive(Debug, Deserialize)]
pub struct OverrideEntry {
    /// Fully-qualified item path, e.g. "my_module::complex_function"
    pub item: String,
    /// Raw Python stub line, e.g. "def complex_function(x: Any, **kwargs: Any) -> dict[str, Any]: ..."
    pub stub: String,
}

/// Version-specific rendering decisions, computed once from the configured Python version
/// and threaded through all generation code.
///
/// Adding a new version-specific behavior means adding a field here and deriving it in
/// `from_version` — no changes needed elsewhere in the generation pipeline.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RenderPolicy {
    /// Emit `T | None` (py ≥ 3.10) instead of `Optional[T]` (py < 3.10).
    pub union_optional: bool,
    /// Emit the native `Self` keyword (py ≥ 3.11, PEP 673) instead of the class name.
    /// When `false`, class names are used as forward references and
    /// `from __future__ import annotations` is added to the output.
    pub native_self: bool,
    /// Prepend `from __future__ import annotations` to the generated file.
    /// Needed when using class names as forward references (i.e. when `!native_self`).
    pub future_annotations: bool,
}

impl RenderPolicy {
    pub fn from_version(major: u32, minor: u32) -> Self {
        let v = (major, minor);
        let native_self = v >= (3, 11);
        Self {
            union_optional: v >= (3, 10),
            native_self,
            // forward-reference class names require lazy annotation evaluation
            future_annotations: !native_self,
        }
    }
}

impl Config {
    /// Load from file if it exists; return default config if the file is absent.
    pub fn load_or_default(path: &Path) -> Result<Self> {
        if !path.exists() {
            return Ok(Self::default());
        }
        let content = std::fs::read_to_string(path)?;
        let config: Self = toml::from_str(&content)?;
        Ok(config)
    }

    /// Return the Python version as (major, minor) tuple for comparison.
    pub fn python_version_tuple(&self) -> (u32, u32) {
        let parts: Vec<u32> = self
            .output
            .python_version
            .split('.')
            .filter_map(|s| s.parse().ok())
            .collect();
        (
            parts.first().copied().unwrap_or(3),
            parts.get(1).copied().unwrap_or(10),
        )
    }

    /// Compute the rendering policy for the configured Python version.
    pub fn render_policy(&self) -> RenderPolicy {
        let (major, minor) = self.python_version_tuple();
        RenderPolicy::from_version(major, minor)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_policy_py39_optional_no_native_self() {
        let p = RenderPolicy::from_version(3, 9);
        assert!(!p.union_optional, "3.9 uses Optional[T]");
        assert!(!p.native_self, "3.9 uses class name, not Self");
        assert!(
            p.future_annotations,
            "3.9 needs future annotations for forward refs"
        );
    }

    #[test]
    fn render_policy_py310_union_optional_no_native_self() {
        let p = RenderPolicy::from_version(3, 10);
        assert!(p.union_optional, "3.10 uses T | None");
        assert!(!p.native_self, "3.10 still uses class name");
        assert!(p.future_annotations);
    }

    #[test]
    fn render_policy_py311_native_self_no_future_annotations() {
        let p = RenderPolicy::from_version(3, 11);
        assert!(p.union_optional);
        assert!(p.native_self, "3.11 has typing.Self (PEP 673)");
        assert!(
            !p.future_annotations,
            "native Self does not require future annotations"
        );
    }

    #[test]
    fn render_policy_py312_same_as_py311() {
        let p = RenderPolicy::from_version(3, 12);
        assert!(p.union_optional);
        assert!(p.native_self);
        assert!(!p.future_annotations);
    }

    #[test]
    fn config_python_version_tuple_parses_major_minor() {
        let mut config = Config::default();
        config.output.python_version = "3.9".to_string();
        assert_eq!(config.python_version_tuple(), (3, 9));

        config.output.python_version = "3.12.0".to_string();
        assert_eq!(config.python_version_tuple(), (3, 12));
    }

    #[test]
    fn config_python_version_tuple_invalid_fallback() {
        let mut config = Config::default();
        config.output.python_version = "invalid".to_string();
        // Fallback: no successful parse → (3, 10) from defaults in implementation
        let (major, minor) = config.python_version_tuple();
        assert_eq!(major, 3);
        assert_eq!(minor, 10);
    }

    #[test]
    fn config_render_policy_uses_configured_version() {
        let mut config = Config::default();
        config.output.python_version = "3.9".to_string();
        let p = config.render_policy();
        assert!(!p.union_optional);
        assert!(p.future_annotations);

        config.output.python_version = "3.12".to_string();
        let p = config.render_policy();
        assert!(p.native_self);
        assert!(!p.future_annotations);
    }

    // ── Config::load_or_default ──────────────────────────────────────────────

    #[test]
    fn load_or_default_returns_default_when_file_absent() {
        let path = std::path::Path::new("/no/such/rylai.toml");
        let config = Config::load_or_default(path).expect("absent file must not error");
        assert_eq!(
            config.output.python_version, "3.10",
            "default python version"
        );
        assert!(config.output.add_header, "header enabled by default");
        assert!(config.type_map.is_empty(), "type_map empty by default");
        assert!(config.overrides.is_empty(), "overrides empty by default");
    }

    #[test]
    fn load_or_default_parses_valid_toml() {
        use std::io::Write;
        let dir = std::env::temp_dir();
        let path = dir.join("rylai_test_valid.toml");
        {
            let mut f = std::fs::File::create(&path).expect("create temp file");
            write!(
                f,
                r#"
[type_map]
"numpy::PyReadonlyArray1" = "numpy.ndarray"

[fallback]
strategy = "error"

[output]
python_version = "3.11"
add_header = false

[[override]]
item = "my_module::my_fn"
stub = "def my_fn() -> int: ..."
"#
            )
            .expect("write temp file");
        }

        let config = Config::load_or_default(&path).expect("valid toml must parse");
        let _ = std::fs::remove_file(&path);

        assert_eq!(
            config
                .type_map
                .get("numpy::PyReadonlyArray1")
                .map(String::as_str),
            Some("numpy.ndarray")
        );
        assert_eq!(config.fallback.strategy, FallbackStrategy::Error);
        assert_eq!(config.output.python_version, "3.11");
        assert!(!config.output.add_header);
        assert_eq!(config.overrides.len(), 1);
        assert_eq!(config.overrides[0].item, "my_module::my_fn");
        assert_eq!(config.overrides[0].stub, "def my_fn() -> int: ...");
    }

    #[test]
    fn load_or_default_errors_on_invalid_toml() {
        use std::io::Write;
        let dir = std::env::temp_dir();
        let path = dir.join("rylai_test_invalid.toml");
        {
            let mut f = std::fs::File::create(&path).expect("create temp file");
            write!(f, "this is not valid = [ toml").expect("write temp file");
        }

        let result = Config::load_or_default(&path);
        let _ = std::fs::remove_file(&path);

        assert!(result.is_err(), "invalid TOML must return Err");
    }

    #[test]
    fn load_or_default_parses_features_enabled() {
        use std::io::Write;
        let mut temp = tempfile::NamedTempFile::new().expect("create temp file");
        write!(
            temp,
            r#"
[features]
enabled = ["default", "extra"]
"#
        )
        .expect("write temp file");
        let path = temp.path();

        let config = Config::load_or_default(path).expect("valid toml must parse");
        assert_eq!(config.features.enabled, ["default", "extra"]);
    }
}
