use anyhow::{Context, Result};
use serde::Deserialize;
use std::collections::HashMap;
use std::path::Path;

#[derive(Debug, Default, Deserialize)]
pub struct Config {
    /// Extra Rust type → Python type overrides (e.g. "numpy::PyReadonlyArray1" = "numpy.ndarray")
    #[serde(default)]
    pub type_map: HashMap<String, String>,

    #[serde(default)]
    pub features: FeaturesConfig,

    #[serde(default)]
    pub fallback: FallbackConfig,

    #[serde(default)]
    pub output: OutputConfig,

    /// Manual stub overrides for specific items
    #[serde(default, rename = "override")]
    pub overrides: Vec<OverrideEntry>,

    /// After generating .pyi files, run these format commands with generated .pyi paths appended.
    /// Each entry is a command string, e.g. "ruff format", "black", "ruff check --select I --fix".
    #[serde(default)]
    pub format: Vec<String>,
}

#[derive(Debug, Default, Deserialize)]
pub struct FeaturesConfig {
    /// cfg features considered active during parsing (used to evaluate #[cfg(feature = "...")]).
    #[serde(default)]
    pub enabled: Vec<String>,
}

#[derive(Debug, Deserialize)]
pub struct FallbackConfig {
    /// What to do when a type cannot be inferred statically:
    /// "any" (default) | "error" | "skip"
    #[serde(default = "default_fallback_strategy")]
    pub strategy: FallbackStrategy,
}

impl Default for FallbackConfig {
    fn default() -> Self {
        Self {
            strategy: FallbackStrategy::Any,
        }
    }
}

#[derive(Debug, Default, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum FallbackStrategy {
    /// Emit `Any` and print a warning (default)
    #[default]
    Any,
    /// Hard error — stop generation and report the unknown type
    Error,
    /// Silently skip items with unresolvable types
    Skip,
}

fn default_fallback_strategy() -> FallbackStrategy {
    FallbackStrategy::Any
}

#[derive(Debug, Deserialize)]
pub struct OutputConfig {
    /// Python version string, affects `t.Optional[T]` vs `T | None` syntax (and related typing output).
    #[serde(default = "default_python_version")]
    pub python_version: String,

    /// Prepend "# Auto-generated by rylai" header
    #[serde(default = "default_true")]
    pub add_header: bool,
}

impl Default for OutputConfig {
    fn default() -> Self {
        Self {
            python_version: default_python_version(),
            add_header: true,
        }
    }
}

fn default_python_version() -> String {
    "3.10".to_string()
}

fn default_true() -> bool {
    true
}

#[derive(Debug, Deserialize)]
pub struct OverrideEntry {
    /// Fully-qualified item path, e.g. "my_module::complex_function"
    pub item: String,
    /// Raw Python stub line, e.g. "def complex_function(x: t.Any, **kwargs: t.Any) -> dict[str, t.Any]: ..."
    pub stub: String,
}

/// Version-specific rendering decisions, computed once from the configured Python version
/// and threaded through all generation code.
///
/// Adding a new version-specific behavior means adding a field here and deriving it in
/// `from_version` — no changes needed elsewhere in the generation pipeline.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RenderPolicy {
    /// Emit `T | None` (py ≥ 3.10) instead of `t.Optional[T]` (py < 3.10).
    pub union_optional: bool,
    /// Emit `t.Self` (py ≥ 3.11, PEP 673) instead of the class name in stubs (`import typing as t`).
    /// When `false`, class names are used as forward references and
    /// `from __future__ import annotations` is added to the output.
    pub native_self: bool,
    /// Prepend `from __future__ import annotations` to the generated file.
    /// Needed when using class names as forward references (i.e. when `!native_self`).
    pub future_annotations: bool,
}

impl RenderPolicy {
    pub fn from_version(major: u32, minor: u32) -> Self {
        let v = (major, minor);
        let native_self = v >= (3, 11);
        Self {
            union_optional: v >= (3, 10),
            native_self,
            // forward-reference class names require lazy annotation evaluation
            future_annotations: !native_self,
        }
    }
}

/// Deep-merge two TOML values; keys in `override_val` take precedence over `base`.
/// Array tables (e.g. `[[override]]`) are replaced as a whole, not merged item-by-item.
fn deep_merge_toml(base: toml::Value, override_val: &toml::Value) -> toml::Value {
    use toml::Value;
    match (base, override_val) {
        (Value::Table(mut base_t), Value::Table(override_t)) => {
            for (k, ov) in override_t {
                let merged = base_t
                    .remove(k.as_str())
                    .map(|b| deep_merge_toml(b, ov))
                    .unwrap_or_else(|| ov.clone());
                base_t.insert(k.clone(), merged);
            }
            Value::Table(base_t)
        }
        (_, override_v) => override_v.clone(),
    }
}

/// Read `[tool.rylai]` from pyproject.toml if present.
fn tool_rylai_from_pyproject(path: &Path) -> Option<toml::Value> {
    let content = std::fs::read_to_string(path).ok()?;
    let doc: toml::Value = content.parse().ok()?;
    doc.get("tool").and_then(|t| t.get("rylai")).cloned()
}

impl Config {
    /// Load config by merging `[tool.rylai]` from pyproject.toml (base) and rylai.toml (override).
    /// When both exist, duplicate keys are resolved in favor of rylai.toml; otherwise both apply.
    pub fn load_merged(rylai_toml_path: &Path, pyproject_path: &Path) -> Result<Self> {
        let base = tool_rylai_from_pyproject(pyproject_path)
            .unwrap_or_else(|| toml::Value::Table(Default::default()));
        let override_val = if rylai_toml_path.exists() {
            let content = std::fs::read_to_string(rylai_toml_path)?;
            toml::from_str(&content).context("parse rylai.toml")?
        } else {
            toml::Value::Table(Default::default())
        };
        let merged = deep_merge_toml(base, &override_val);
        let config: Self = merged
            .try_into()
            .map_err(|e| anyhow::anyhow!("invalid config structure: {}", e))?;
        Ok(config)
    }

    /// Return the Python version as (major, minor) tuple for comparison.
    pub fn python_version_tuple(&self) -> (u32, u32) {
        let parts: Vec<u32> = self
            .output
            .python_version
            .split('.')
            .filter_map(|s| s.parse().ok())
            .collect();
        (
            parts.first().copied().unwrap_or(3),
            parts.get(1).copied().unwrap_or(10),
        )
    }

    /// Compute the rendering policy for the configured Python version.
    pub fn render_policy(&self) -> RenderPolicy {
        let (major, minor) = self.python_version_tuple();
        RenderPolicy::from_version(major, minor)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_policy_py39_optional_no_native_self() {
        let p = RenderPolicy::from_version(3, 9);
        assert!(!p.union_optional, "3.9 uses t.Optional[T]");
        assert!(!p.native_self, "3.9 uses class name, not Self");
        assert!(
            p.future_annotations,
            "3.9 needs future annotations for forward refs"
        );
    }

    #[test]
    fn render_policy_py310_union_optional_no_native_self() {
        let p = RenderPolicy::from_version(3, 10);
        assert!(p.union_optional, "3.10 uses T | None");
        assert!(!p.native_self, "3.10 still uses class name");
        assert!(p.future_annotations);
    }

    #[test]
    fn render_policy_py311_native_self_no_future_annotations() {
        let p = RenderPolicy::from_version(3, 11);
        assert!(p.union_optional);
        assert!(p.native_self, "3.11 has typing.Self (PEP 673)");
        assert!(
            !p.future_annotations,
            "native Self does not require future annotations"
        );
    }

    #[test]
    fn render_policy_py312_same_as_py311() {
        let p = RenderPolicy::from_version(3, 12);
        assert!(p.union_optional);
        assert!(p.native_self);
        assert!(!p.future_annotations);
    }

    #[test]
    fn config_python_version_tuple_parses_major_minor() {
        let mut config = Config::default();
        config.output.python_version = "3.9".to_string();
        assert_eq!(config.python_version_tuple(), (3, 9));

        config.output.python_version = "3.12.0".to_string();
        assert_eq!(config.python_version_tuple(), (3, 12));
    }

    #[test]
    fn config_python_version_tuple_invalid_fallback() {
        let mut config = Config::default();
        config.output.python_version = "invalid".to_string();
        // Fallback: no successful parse → (3, 10) from defaults in implementation
        let (major, minor) = config.python_version_tuple();
        assert_eq!(major, 3);
        assert_eq!(minor, 10);
    }

    #[test]
    fn config_render_policy_uses_configured_version() {
        let mut config = Config::default();
        config.output.python_version = "3.9".to_string();
        let p = config.render_policy();
        assert!(!p.union_optional);
        assert!(p.future_annotations);

        config.output.python_version = "3.12".to_string();
        let p = config.render_policy();
        assert!(p.native_self);
        assert!(!p.future_annotations);
    }

    // ── Config::load_merged ───────────────────────────────────────────────────

    #[test]
    fn load_merged_returns_default_when_both_absent() {
        let dir = tempfile::tempdir().expect("tempdir");
        let rylai_toml = dir.path().join("no_rylai_absent.toml");
        let pyproject = dir.path().join("no_pyproject_absent.toml");
        let config =
            Config::load_merged(&rylai_toml, &pyproject).expect("absent files must not error");
        assert_eq!(
            config.output.python_version, "3.10",
            "default python version"
        );
        assert!(config.output.add_header, "header enabled by default");
        assert!(config.type_map.is_empty(), "type_map empty by default");
        assert!(config.overrides.is_empty(), "overrides empty by default");
    }

    #[test]
    fn load_merged_parses_valid_rylai_toml_only() {
        use std::io::Write;
        let dir = tempfile::tempdir().expect("tempdir");
        let rylai_toml = dir.path().join("rylai_merged_valid.toml");
        let pyproject = dir.path().join("pyproject_merged_nonexist.toml");
        {
            let mut f = std::fs::File::create(&rylai_toml).expect("create temp file");
            write!(
                f,
                r#"
[type_map]
"numpy::PyReadonlyArray1" = "numpy.ndarray"

[fallback]
strategy = "error"

[output]
python_version = "3.11"
add_header = false

[[override]]
item = "my_module::my_fn"
stub = "def my_fn() -> int: ..."
"#
            )
            .expect("write temp file");
        }

        let config = Config::load_merged(&rylai_toml, &pyproject).expect("valid toml must parse");

        assert_eq!(
            config
                .type_map
                .get("numpy::PyReadonlyArray1")
                .map(String::as_str),
            Some("numpy.ndarray")
        );
        assert_eq!(config.fallback.strategy, FallbackStrategy::Error);
        assert_eq!(config.output.python_version, "3.11");
        assert!(!config.output.add_header);
        assert_eq!(config.overrides.len(), 1);
        assert_eq!(config.overrides[0].item, "my_module::my_fn");
        assert_eq!(config.overrides[0].stub, "def my_fn() -> int: ...");
    }

    #[test]
    fn load_merged_invalid_rylai_toml_errors() {
        use std::io::Write;
        let dir = tempfile::tempdir().expect("tempdir");
        let rylai_toml = dir.path().join("rylai_merged_invalid.toml");
        let pyproject = dir.path().join("pyproject_merged_nonexist2.toml");
        {
            let mut f = std::fs::File::create(&rylai_toml).expect("create temp file");
            write!(f, "this is not valid = [ toml").expect("write temp file");
        }

        let result = Config::load_merged(&rylai_toml, &pyproject);
        assert!(result.is_err(), "invalid rylai.toml must return Err");
        let err = result.unwrap_err();
        assert!(
            err.to_string().contains("parse rylai.toml") || err.to_string().contains("toml"),
            "error should mention rylai.toml or toml: {}",
            err
        );
    }

    #[test]
    fn load_merged_parses_features_from_rylai_toml() {
        use std::io::Write;
        let dir = tempfile::tempdir().expect("tempdir");
        let rylai_toml = dir.path().join("rylai_merged_features.toml");
        let pyproject = dir.path().join("pyproject_merged_nonexist3.toml");
        {
            let mut f = std::fs::File::create(&rylai_toml).expect("create temp file");
            write!(
                f,
                r#"
[features]
enabled = ["default", "extra"]
"#
            )
            .expect("write temp file");
        }

        let config = Config::load_merged(&rylai_toml, &pyproject).expect("valid toml must parse");
        assert_eq!(config.features.enabled, ["default", "extra"]);
    }

    #[test]
    fn load_merged_only_pyproject() {
        use std::io::Write;
        let dir = tempfile::tempdir().expect("tempdir");
        let pyproject = dir.path().join("pyproject_merge_test.toml");
        let rylai_toml = dir.path().join("rylai_merge_nonexist.toml");
        {
            let mut f = std::fs::File::create(&pyproject).expect("create");
            write!(
                f,
                r#"
[project]
name = "test"

[tool.rylai.output]
python_version = "3.9"
add_header = false

[tool.rylai.fallback]
strategy = "skip"
"#
            )
            .expect("write");
        }

        let config = Config::load_merged(&rylai_toml, &pyproject).expect("merge must succeed");
        assert_eq!(config.output.python_version, "3.9");
        assert!(!config.output.add_header);
        assert_eq!(config.fallback.strategy, FallbackStrategy::Skip);
    }

    #[test]
    fn load_merged_pyproject_parses_override_array() {
        use std::io::Write;
        let dir = tempfile::tempdir().expect("tempdir");
        let pyproject = dir.path().join("pyproject_override_array_test.toml");
        let rylai_toml = dir.path().join("rylai_nonexist_override_test.toml");
        {
            let mut f = std::fs::File::create(&pyproject).expect("create");
            write!(
                f,
                r#"
[project]
name = "test"

[tool.rylai.output]
python_version = "3.11"

[[tool.rylai.override]]
item = "my_module::complex_function"
stub = "def complex_function(x: t.Any, **kwargs: t.Any) -> dict[str, t.Any]: ..."

[[tool.rylai.override]]
item = "other::fn"
stub = "def fn() -> int: ..."
"#
            )
            .expect("write");
        }

        let config = Config::load_merged(&rylai_toml, &pyproject).expect("merge must succeed");
        assert_eq!(config.output.python_version, "3.11");
        assert_eq!(config.overrides.len(), 2);
        assert_eq!(config.overrides[0].item, "my_module::complex_function");
        assert_eq!(
            config.overrides[0].stub,
            "def complex_function(x: t.Any, **kwargs: t.Any) -> dict[str, t.Any]: ..."
        );
        assert_eq!(config.overrides[1].item, "other::fn");
        assert_eq!(config.overrides[1].stub, "def fn() -> int: ...");
    }

    #[test]
    fn load_merged_parses_format_commands() {
        use std::io::Write;
        let dir = tempfile::tempdir().expect("tempdir");
        let rylai_toml = dir.path().join("rylai_format_test.toml");
        let pyproject = dir.path().join("pyproject_nonexist.toml");
        {
            let mut f = std::fs::File::create(&rylai_toml).expect("create");
            write!(
                f,
                r#"
format = ["ruff format", "ruff check --select I --fix", "black"]
"#
            )
            .expect("write");
        }

        let config = Config::load_merged(&rylai_toml, &pyproject).expect("valid toml must parse");
        assert_eq!(config.format.len(), 3);
        assert_eq!(config.format[0], "ruff format");
        assert_eq!(config.format[1], "ruff check --select I --fix");
        assert_eq!(config.format[2], "black");
    }

    #[test]
    fn load_merged_rylai_toml_overrides_duplicate_keys() {
        use std::io::Write;
        let dir = tempfile::tempdir().expect("tempdir");
        let pyproject = dir.path().join("pyproject_override_test.toml");
        let rylai_toml = dir.path().join("rylai_override_test.toml");
        {
            let mut f = std::fs::File::create(&pyproject).expect("create");
            write!(
                f,
                r#"
[project]
name = "test"

[tool.rylai.output]
python_version = "3.9"
add_header = true

[tool.rylai.type_map]
"foo::Bar" = "bar.Foo"
"only::Pyproject" = "pyproject.Only"
"#
            )
            .expect("write");
        }
        {
            let mut f = std::fs::File::create(&rylai_toml).expect("create");
            write!(
                f,
                r#"
[output]
python_version = "3.12"
add_header = false

[type_map]
"foo::Bar" = "rylai.Wins"
"only::Rylai" = "rylai.Only"
"#
            )
            .expect("write");
        }

        let config = Config::load_merged(&rylai_toml, &pyproject).expect("merge must succeed");
        // Duplicate keys: rylai.toml wins
        assert_eq!(config.output.python_version, "3.12");
        assert!(!config.output.add_header);
        assert_eq!(
            config.type_map.get("foo::Bar").map(String::as_str),
            Some("rylai.Wins")
        );
        // Non-duplicate: both apply
        assert_eq!(
            config.type_map.get("only::Pyproject").map(String::as_str),
            Some("pyproject.Only")
        );
        assert_eq!(
            config.type_map.get("only::Rylai").map(String::as_str),
            Some("rylai.Only")
        );
    }
}
