use crate::collector::{
    MethodKind, ParamKind, PyClass, PyConstant, PyFunction, PyItem, PyMethod, PyModule, PyParam,
    PyType,
};
use crate::config::{Config, FallbackStrategy, RenderPolicy};
use crate::type_map::{self, TypeMapping};
use anyhow::{Result, bail};
use std::collections::HashMap;

// ── Public entry point ───────────────────────────────────────────────────────

pub fn generate(modules: &[PyModule], config: &Config) -> Result<String> {
    let (known_classes, pre_warnings) = collect_class_names(modules);
    generate_with_known_classes(modules, config, &known_classes, &pre_warnings)
}

/// Generate .pyi content for the given modules using a pre-computed Rust→Python class name map.
/// Used when emitting multiple stubs so that cross-module type references resolve correctly.
pub fn generate_with_known_classes(
    modules: &[PyModule],
    config: &Config,
    known_classes: &HashMap<String, String>,
    pre_warnings: &[String],
) -> Result<String> {
    let policy = config.render_policy();
    let mut ctx = GenCtx {
        config,
        policy,
        needs_any: false,
        needs_optional: false,
        needs_self_import: false,
        needs_path_import: false,
        needs_union: false,
        needs_final: false,
        warnings: pre_warnings.to_vec(),
        current_self_type: None,
        known_classes: known_classes.clone(),
    };

    let mut body = String::new();
    for module in modules {
        ctx.gen_module(module, &mut body, 0)?;
    }

    let mut out = String::new();

    // Header
    if config.output.add_header {
        out.push_str("# Auto-generated by rylai. Do not edit manually.\n\n");
    }

    // `from __future__ import annotations` enables lazy annotation evaluation, which
    // is required when py < 3.11: class names are used as forward references in return
    // types (e.g. `def from_bytes(...) -> PdfDocument`).
    if ctx.policy.future_annotations {
        out.push_str("from __future__ import annotations\n\n");
    }

    // typing imports
    let mut typing_parts: Vec<&str> = Vec::new();
    if ctx.needs_any {
        typing_parts.push("Any");
    }
    if ctx.needs_optional {
        typing_parts.push("Optional");
    }
    if ctx.needs_self_import {
        typing_parts.push("Self");
    }
    if ctx.needs_union {
        typing_parts.push("Union");
    }
    if ctx.needs_final {
        typing_parts.push("Final");
    }
    if !typing_parts.is_empty() {
        out.push_str(&format!(
            "from typing import {}\n\n",
            typing_parts.join(", ")
        ));
    }

    if ctx.needs_path_import {
        out.push_str("from pathlib import Path\n\n");
    }

    out.push_str(&body);

    // Print warnings to stderr
    for w in &ctx.warnings {
        eprintln!("warning: {w}");
    }

    Ok(out)
}

// ── Generation context ───────────────────────────────────────────────────────

/// Restores `GenCtx::current_self_type` to `None` when dropped so that early returns
/// (e.g. via `?`) from `gen_method` do not leave the context in a stale state.
struct RestoreCurrentSelfTypeGuard(*mut Option<String>);

impl Drop for RestoreCurrentSelfTypeGuard {
    fn drop(&mut self) {
        // SAFETY: the pointer is taken from `&mut self.current_self_type` in `gen_method`
        // and is only used while that method is running; the guard is dropped on return.
        unsafe {
            *self.0 = None;
        }
    }
}

struct GenCtx<'a> {
    config: &'a Config,
    /// Version-specific rendering decisions derived from config at the start of generation.
    policy: RenderPolicy,
    needs_any: bool,
    needs_optional: bool,
    /// Whether any mapping emitted the `Self` keyword (py ≥ 3.11, PEP 673).
    needs_self_import: bool,
    /// Whether any mapping used pathlib.Path (Rust PathBuf/Path → Path | str).
    needs_path_import: bool,
    /// Whether any mapping used Union[...] (py < 3.10 style, e.g. Union[Path, str]).
    needs_union: bool,
    /// Whether any module-level constant was emitted (needs `from typing import Final`).
    needs_final: bool,
    warnings: Vec<String>,
    /// Set to the Python class name while generating methods for that class,
    /// so that Rust `Self` return types resolve correctly.
    current_self_type: Option<String>,
    /// Maps each `#[pyclass]` Rust struct name to its Python-visible class name, collected
    /// before generation starts.  This allows return types like `-> PyResult<PyPageIterator>`
    /// (where the Rust struct is `PyPageIterator` but the Python name is `PageIterator`) to
    /// resolve correctly instead of falling back to `Any`.
    known_classes: HashMap<String, String>,
}

impl<'a> GenCtx<'a> {
    fn resolve_type(&mut self, py_type: &PyType, location: &str) -> Result<String> {
        // User override takes priority
        if let Some(ov) = &py_type.override_str {
            return Ok(ov.clone());
        }

        let mapping = type_map::map_type(
            &py_type.rust_type,
            &self.policy,
            self.current_self_type.as_deref(),
            &self.known_classes,
        );
        self.absorb_mapping(&mapping, location)?;
        Ok(mapping.py_type)
    }

    fn absorb_mapping(&mut self, m: &TypeMapping, location: &str) -> Result<()> {
        if m.needs_any {
            self.needs_any = true;
        }
        if m.needs_optional {
            self.needs_optional = true;
        }
        if m.needs_self_import {
            self.needs_self_import = true;
        }
        if m.needs_path_import {
            self.needs_path_import = true;
        }
        if m.needs_union {
            self.needs_union = true;
        }
        if m.is_unknown {
            match self.config.fallback.strategy {
                FallbackStrategy::Any => {
                    self.warnings.push(format!(
                        "unknown type at `{location}` — falling back to `Any`"
                    ));
                }
                FallbackStrategy::Error => {
                    bail!("unknown type at `{location}` and fallback strategy is `error`");
                }
                FallbackStrategy::Skip => {
                    // Caller checks is_unknown and skips the item
                }
            }
        }
        Ok(())
    }

    // ── Module ───────────────────────────────────────────────────────────────

    fn gen_module(&mut self, module: &PyModule, out: &mut String, indent: usize) -> Result<()> {
        let pad = "    ".repeat(indent);

        if !module.doc.is_empty() {
            out.push_str(&format!("{pad}# Module: {}\n", module.name));
        }

        for item in &module.items {
            // Check for manual override
            let override_stub = self.config.overrides.iter().find(|o| {
                o.item.ends_with(&format!("::{}", item_name(item))) || o.item == item_name(item)
            });
            if let Some(ov) = override_stub {
                out.push_str(&format!("{pad}{}\n\n", ov.stub));
                continue;
            }

            match item {
                PyItem::Constant(c) => self.gen_constant(c, out, indent)?,
                PyItem::Function(f) => self.gen_function(f, out, indent)?,
                PyItem::Class(c) => self.gen_class(c, out, indent)?,
                PyItem::Module(m) => {
                    // Submodule: emit a class stub as a namespace approximation
                    out.push_str(&format!("{pad}class {}:\n", m.name));
                    if !m.doc.is_empty() {
                        self.gen_docstring(&m.doc, out, indent + 1);
                    }
                    self.gen_module(m, out, indent + 1)?;
                    out.push('\n');
                }
            }
        }
        Ok(())
    }

    // ── Module-level constant (m.add("name", value)) ─────────────────────────

    /// Emits `name: Final[py_type]` and sets `needs_final` so that `from typing import Final` is included.
    fn gen_constant(&mut self, c: &PyConstant, out: &mut String, indent: usize) -> Result<()> {
        self.needs_final = true;
        let pad = "    ".repeat(indent);
        out.push_str(&format!("{pad}{}: Final[{}]\n", c.name, c.py_type));
        Ok(())
    }

    // ── Function ─────────────────────────────────────────────────────────────

    fn gen_function(&mut self, f: &PyFunction, out: &mut String, indent: usize) -> Result<()> {
        let pad = "    ".repeat(indent);
        let ret = self.resolve_type(&f.return_type, &format!("{}::return", f.name))?;

        let params_str = if let Some(sig) = &f.signature_override {
            // #[pyo3(signature = (...))] is present: merge signature defaults with Rust types
            self.merge_sig_with_types(sig, &f.params, &f.name)?
        } else {
            self.gen_params(&f.params, &f.name, false)?
        };

        out.push_str(&format!("{pad}def {}({params_str}) -> {ret}:\n", f.name));

        if !f.doc.is_empty() {
            self.gen_docstring(&f.doc, out, indent + 1);
        } else {
            out.push_str(&format!("{pad}    ...\n"));
        }
        out.push('\n');
        Ok(())
    }

    // ── Class ────────────────────────────────────────────────────────────────

    fn gen_class(&mut self, c: &PyClass, out: &mut String, indent: usize) -> Result<()> {
        let pad = "    ".repeat(indent);
        out.push_str(&format!("{pad}class {}:\n", c.name));

        if !c.doc.is_empty() {
            self.gen_docstring(&c.doc, out, indent + 1);
        }

        if c.methods.is_empty() {
            out.push_str(&format!("{pad}    ...\n"));
        } else {
            for method in &c.methods {
                self.gen_method(method, &c.name, out, indent + 1)?;
            }
        }
        out.push('\n');
        Ok(())
    }

    fn gen_method(
        &mut self,
        m: &PyMethod,
        class_name: &str,
        out: &mut String,
        indent: usize,
    ) -> Result<()> {
        self.current_self_type = Some(class_name.to_string());
        let _guard =
            RestoreCurrentSelfTypeGuard(&mut self.current_self_type as *mut Option<String>);
        let pad = "    ".repeat(indent);
        let location = format!("{}::{}", class_name, m.name);
        let ret = self.resolve_type(&m.return_type, &format!("{location}::return"))?;

        match &m.kind {
            MethodKind::New => {
                let params = self.method_params(m, &location, true)?;
                out.push_str(&format!("{pad}def __init__({params}) -> None:\n"));
            }
            MethodKind::Static => {
                out.push_str(&format!("{pad}@staticmethod\n"));
                let params = self.method_params(m, &location, false)?;
                out.push_str(&format!("{pad}def {}({params}) -> {ret}:\n", m.name));
            }
            MethodKind::Class => {
                out.push_str(&format!("{pad}@classmethod\n"));
                let params = self.method_params(m, &location, true)?;
                out.push_str(&format!("{pad}def {}({params}) -> {ret}:\n", m.name));
            }
            MethodKind::Getter(prop) => {
                out.push_str(&format!("{pad}@property\n"));
                out.push_str(&format!("{pad}def {prop}(self) -> {ret}:\n"));
            }
            MethodKind::Setter(prop) => {
                // setter takes one value param
                let val_type = m
                    .params
                    .first()
                    .map(|p| self.resolve_type(&p.ty, &location))
                    .transpose()?
                    .unwrap_or_else(|| "Any".to_string());
                if val_type == "Any" {
                    self.needs_any = true;
                }
                out.push_str(&format!("{pad}@{prop}.setter\n"));
                out.push_str(&format!(
                    "{pad}def {prop}(self, value: {val_type}) -> None:\n"
                ));
            }
            MethodKind::Instance => {
                let params = self.method_params(m, &location, true)?;
                out.push_str(&format!("{pad}def {}({params}) -> {ret}:\n", m.name));
            }
        }

        if !m.doc.is_empty() {
            self.gen_docstring(&m.doc, out, indent + 1);
        } else {
            out.push_str(&format!("{pad}    ...\n"));
        }
        out.push('\n');
        Ok(())
    }

    /// Build the parameter list for a method: uses `signature_override` when present,
    /// otherwise `gen_params`. When `with_self` is true, the result includes a leading `self`.
    fn method_params(&mut self, m: &PyMethod, location: &str, with_self: bool) -> Result<String> {
        if let Some(sig) = &m.signature_override {
            let merged = self.merge_sig_with_types(sig, &m.params, location)?;
            Ok(if with_self {
                format!("self, {merged}")
            } else {
                merged
            })
        } else {
            self.gen_params(&m.params, location, with_self)
        }
    }

    // ── Signature merge ──────────────────────────────────────────────────────

    /// Combine a `#[pyo3(signature = (...))]` string with the Rust param types.
    ///
    /// `sig` is the inner content of the signature attribute with outer parens already
    /// stripped, e.g. `"page=None, clip=None, tf_settings=None, **kwargs"`.
    /// For every name found in `params` we attach the mapped Python type; entries that
    /// have no Rust counterpart (e.g. a sentinel `/`) are emitted verbatim.
    fn merge_sig_with_types(
        &mut self,
        sig: &str,
        params: &[PyParam],
        fn_name: &str,
    ) -> Result<String> {
        // Build name → PyParam lookup
        let param_by_name: HashMap<&str, &PyParam> =
            params.iter().map(|p| (p.name.as_str(), p)).collect();

        let raw_parts = split_at_top_level_commas(sig);
        let mut out_parts: Vec<String> = Vec::new();

        for raw in raw_parts {
            let token = raw.trim();
            if token.is_empty() {
                continue;
            }

            if let Some(name) = token.strip_prefix("**") {
                let name = name.trim(); // proc-macro may emit "** kwargs" with a space
                // **kwargs are unpacked; no type (Unpack[TypedDict] etc. not supported yet).
                out_parts.push(format!("**{name}"));
            } else if let Some(name) = token.strip_prefix('*') {
                let name = name.trim();
                if name.is_empty() {
                    // bare `*` — keyword-only argument separator
                    out_parts.push("*".to_string());
                } else {
                    // *args are unpacked; no type.
                    out_parts.push(format!("*{name}"));
                }
            } else {
                let (name, default_opt) = split_name_default(token);
                if let Some(p) = param_by_name.get(name) {
                    let ty = self.resolve_type(&p.ty, &format!("{fn_name}::{name}"))?;
                    match default_opt {
                        Some(default) => out_parts.push(format!("{name}: {ty} = {default}")),
                        None => out_parts.push(format!("{name}: {ty}")),
                    }
                } else {
                    // No Rust type available — keep the signature token as-is
                    out_parts.push(token.to_string());
                }
            }
        }

        Ok(out_parts.join(", "))
    }

    // ── Params ───────────────────────────────────────────────────────────────

    fn gen_params(
        &mut self,
        params: &[PyParam],
        location: &str,
        with_self: bool,
    ) -> Result<String> {
        let mut parts: Vec<String> = Vec::new();
        if with_self {
            parts.push("self".to_string());
        }
        for p in params {
            let ty = self.resolve_type(&p.ty, &format!("{location}::{}", p.name))?;
            let part = match p.kind {
                ParamKind::Args => format!("*{}: {ty}", p.name),
                ParamKind::Kwargs => format!("**{}: {ty}", p.name),
                ParamKind::Regular => {
                    if let Some(default) = &p.default {
                        format!("{}: {} = {}", p.name, ty, default)
                    } else {
                        format!("{}: {ty}", p.name)
                    }
                }
            };
            parts.push(part);
        }
        Ok(parts.join(", "))
    }

    // ── Docstring ────────────────────────────────────────────────────────────

    fn gen_docstring(&self, lines: &[String], out: &mut String, indent: usize) {
        let pad = "    ".repeat(indent);
        if lines.len() == 1 {
            out.push_str(&format!("{pad}\"\"\"{}\"\"\"\n", lines[0]));
        } else {
            out.push_str(&format!("{pad}\"\"\"\n"));
            for line in lines {
                out.push_str(&format!("{pad}{line}\n"));
            }
            out.push_str(&format!("{pad}\"\"\"\n"));
        }
    }
}

// ── Helpers ──────────────────────────────────────────────────────────────────

/// Recursively collect all `#[pyclass]` entries from a slice of modules, returning a map
/// from Rust struct/enum name → Python class name, plus any collision warnings.
///
/// When the Rust struct and the Python class share the same name (no `name = "..."` attr)
/// both key and value are identical.  When they differ (e.g. `PyPageIterator` → `PageIterator`)
/// the Rust name is the key so that type-signature lookups can resolve the correct Python name.
///
/// If two `#[pyclass]` items in different modules share the same Rust name but map to
/// different Python names, the first registration wins and a warning is emitted.
pub fn collect_class_names(modules: &[PyModule]) -> (HashMap<String, String>, Vec<String>) {
    let mut map = HashMap::new();
    let mut warnings = Vec::new();
    for m in modules {
        collect_class_names_from_module(m, &mut map, &mut warnings);
    }
    (map, warnings)
}

fn collect_class_names_from_module(
    m: &PyModule,
    map: &mut HashMap<String, String>,
    warnings: &mut Vec<String>,
) {
    for item in &m.items {
        match item {
            PyItem::Class(c) => {
                if let Some(existing) = map.get(&c.rust_name) {
                    if existing != &c.name {
                        warnings.push(format!(
                            "Rust type `{}` is registered as both `{}` and `{}` — \
                             using `{}`. Rename one struct or add `#[pyclass(name = \"...\")]`.",
                            c.rust_name, existing, c.name, existing
                        ));
                    }
                } else {
                    map.insert(c.rust_name.clone(), c.name.clone());
                }
            }
            PyItem::Module(sub) => collect_class_names_from_module(sub, map, warnings),
            PyItem::Function(_) | PyItem::Constant(_) => {}
        }
    }
}

fn item_name(item: &PyItem) -> &str {
    match item {
        PyItem::Constant(c) => &c.name,
        PyItem::Function(f) => &f.name,
        PyItem::Class(c) => &c.name,
        PyItem::Module(m) => &m.name,
    }
}

/// Split a parameter-list string at top-level commas, respecting nested brackets.
///
/// For example, `"a, b=(1,2), **kwargs"` yields `["a", " b=(1,2)", " **kwargs"]`.
///
/// Unbalanced brackets (malformed input) are tolerated: depth uses saturating_sub
/// so the function continues and produces best-effort output rather than panicking.
fn split_at_top_level_commas(s: &str) -> Vec<&str> {
    let mut parts = Vec::new();
    let mut depth: usize = 0;
    let mut start = 0;
    for (i, ch) in s.char_indices() {
        match ch {
            '(' | '[' | '{' => depth += 1,
            ')' | ']' | '}' => depth = depth.saturating_sub(1),
            ',' if depth == 0 => {
                parts.push(&s[start..i]);
                start = i + 1;
            }
            _ => {}
        }
    }
    parts.push(&s[start..]);
    parts
}

/// Split a signature token such as `"page=None"` into `("page", Some("None"))`.
/// Tokens without a `=` return `(token, None)`.
/// Only the **first** `=` is used as the split point.
fn split_name_default(token: &str) -> (&str, Option<&str>) {
    match token.find('=') {
        Some(pos) => (token[..pos].trim(), Some(token[pos + 1..].trim())),
        None => (token.trim(), None),
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::collector::{
        MethodKind, ParamKind, PyClass, PyConstant, PyFunction, PyItem, PyMethod, PyModule,
        PyParam, PyType,
    };
    use crate::config::Config;
    use std::path::PathBuf;

    // ── Test-data builders ───────────────────────────────────────────────────

    fn dummy_path() -> PathBuf {
        PathBuf::from("test.rs")
    }

    fn make_module(items: Vec<PyItem>) -> PyModule {
        PyModule {
            name: "m".to_string(),
            doc: vec![],
            items,
            source_file: dummy_path(),
        }
    }

    fn make_fn(name: &str, sig: Option<&str>, params: Vec<PyParam>, ret: syn::Type) -> PyFunction {
        PyFunction {
            name: name.to_string(),
            doc: vec![],
            signature_override: sig.map(str::to_string),
            params,
            return_type: PyType {
                rust_type: ret,
                override_str: None,
            },
            source_file: dummy_path(),
        }
    }

    fn make_param(name: &str, rust_type: syn::Type) -> PyParam {
        PyParam {
            name: name.to_string(),
            ty: PyType {
                rust_type,
                override_str: None,
            },
            default: None,
            kind: ParamKind::Regular,
        }
    }

    /// Build a class with one static method that returns PyResult<Self> (e.g. from_bytes).
    fn make_class_with_self_return(class_name: &str, method_name: &str) -> PyClass {
        PyClass {
            name: class_name.to_string(),
            rust_name: class_name.to_string(),
            module: None,
            doc: vec![],
            methods: vec![PyMethod {
                name: method_name.to_string(),
                doc: vec![],
                kind: MethodKind::Static,
                signature_override: None,
                params: vec![make_param("data", syn::parse_quote! { &[u8] })],
                return_type: PyType {
                    rust_type: syn::parse_quote! { pyo3::PyResult<Self> },
                    override_str: None,
                },
            }],
            source_file: dummy_path(),
        }
    }

    fn stub_for(items: Vec<PyItem>) -> String {
        let config = Config::default();
        generate(&[make_module(items)], &config).unwrap()
    }

    fn config_with_python_version(version: &str) -> Config {
        let mut config = Config::default();
        config.output.python_version = version.to_string();
        config
    }

    fn stub_for_config(items: Vec<PyItem>, config: &Config) -> String {
        generate(&[make_module(items)], config).unwrap()
    }

    /// generate_with_known_classes resolves return types using the provided map,
    /// so a function in the root stub that returns a class from another stub (e.g. Layer)
    /// emits the class name, not Any.
    #[test]
    fn generate_with_known_classes_resolves_cross_module_class_in_return_type() {
        let root_module = make_module(vec![PyItem::Function(make_fn(
            "get_layer",
            None,
            vec![],
            syn::parse_quote! { pyo3::PyResult<Layer> },
        ))]);
        let mut known_classes = HashMap::new();
        known_classes.insert("Layer".to_string(), "Layer".to_string());
        let stub =
            generate_with_known_classes(&[root_module], &Config::default(), &known_classes, &[])
                .unwrap();
        assert!(
            stub.contains("-> Layer"),
            "return type should resolve to Layer from known_classes, not Any; got:\n{stub}"
        );
    }

    // ── split_at_top_level_commas ────────────────────────────────────────────

    #[test]
    fn split_simple_list() {
        assert_eq!(split_at_top_level_commas("a, b, c"), vec!["a", " b", " c"]);
    }

    #[test]
    fn split_respects_nested_parens() {
        // The comma inside (1,2) must not split the token
        let parts = split_at_top_level_commas("a, b=(1,2), c");
        assert_eq!(parts, vec!["a", " b=(1,2)", " c"]);
    }

    #[test]
    fn split_single_token() {
        assert_eq!(split_at_top_level_commas("page=None"), vec!["page=None"]);
    }

    #[test]
    fn split_with_kwargs() {
        let parts = split_at_top_level_commas("page=None, **kwargs");
        assert_eq!(parts, vec!["page=None", " **kwargs"]);
    }

    #[test]
    fn split_nested_brackets_and_braces() {
        let parts = split_at_top_level_commas("a, b=[1,2], c={3}");
        assert_eq!(parts, vec!["a", " b=[1,2]", " c={3}"]);
    }

    // ── split_name_default ───────────────────────────────────────────────────

    #[test]
    fn name_default_with_none() {
        assert_eq!(split_name_default("page=None"), ("page", Some("None")));
    }

    #[test]
    fn name_default_with_bool() {
        assert_eq!(
            split_name_default("extract_text=True"),
            ("extract_text", Some("True"))
        );
    }

    #[test]
    fn name_default_absent() {
        assert_eq!(split_name_default("cells"), ("cells", None));
    }

    #[test]
    fn name_default_trims_whitespace() {
        // Signature tokens extracted by pyo3 often have surrounding spaces
        assert_eq!(split_name_default(" page = None "), ("page", Some("None")));
    }

    #[test]
    fn name_default_tuple_default() {
        // Only the first `=` is used; value may contain `=` in a nested expression
        assert_eq!(split_name_default("clip=(1,2)"), ("clip", Some("(1,2)")));
    }

    // ── merge_sig_with_types (via generate) ──────────────────────────────────

    /// Regular params with defaults get their Rust types attached.
    #[test]
    fn merge_attaches_type_and_preserves_default() {
        let f = make_fn(
            "find_cells",
            Some("page=None, clip=None"),
            vec![
                make_param("page", syn::parse_quote! { Option<i32> }),
                make_param("clip", syn::parse_quote! { Option<String> }),
            ],
            syn::parse_quote! { Vec<i32> },
        );
        let stub = stub_for(vec![PyItem::Function(f)]);
        assert!(stub.contains("page: int | None = None"), "got:\n{stub}");
        assert!(stub.contains("clip: str | None = None"), "got:\n{stub}");
    }

    /// Required params (no default in signature) get typed but no `= ...`.
    #[test]
    fn merge_required_param_no_default() {
        let f = make_fn(
            "proc",
            Some("cells, extract_text"),
            vec![
                make_param("cells", syn::parse_quote! { Vec<i32> }),
                make_param("extract_text", syn::parse_quote! { bool }),
            ],
            syn::parse_quote! { () },
        );
        let stub = stub_for(vec![PyItem::Function(f)]);
        assert!(stub.contains("cells: list[int]"), "got:\n{stub}");
        assert!(stub.contains("extract_text: bool"), "got:\n{stub}");
        // Must not gain a spurious default
        assert!(!stub.contains("cells: list[int] ="), "got:\n{stub}");
    }

    /// `**kwargs` is emitted without a type (no Unpack[TypedDict] etc. for now).
    #[test]
    fn merge_kwargs_no_type() {
        let f = make_fn(
            "my_fn",
            Some("page=None, **kwargs"),
            vec![
                make_param("page", syn::parse_quote! { Option<i32> }),
                make_param("kwargs", syn::parse_quote! { Option<i32> }),
            ],
            syn::parse_quote! { () },
        );
        let stub = stub_for(vec![PyItem::Function(f)]);
        assert!(stub.contains("**kwargs"), "got:\n{stub}");
        assert!(
            !stub.contains("**kwargs:"),
            "**kwargs should have no type annotation, got:\n{stub}"
        );
    }

    /// When signature has regular params before *args and **kwargs, regular params keep their types.
    #[test]
    fn merge_mixed_args_kwargs_regular_params_typed() {
        let f = make_fn(
            "find_tables",
            Some("page=None, clip=None, *args, **kwargs"),
            vec![
                make_param("page", syn::parse_quote! { Option<i32> }),
                make_param("clip", syn::parse_quote! { Option<f64> }),
                make_param("args", syn::parse_quote! { Vec<String> }),
                make_param(
                    "kwargs",
                    syn::parse_quote! { Option<pyo3::Bound<'_, pyo3::types::PyDict>> },
                ),
            ],
            syn::parse_quote! { () },
        );
        let stub = stub_for(vec![PyItem::Function(f)]);
        assert!(stub.contains("page: "), "page must have type, got:\n{stub}");
        assert!(stub.contains("clip: "), "clip must have type, got:\n{stub}");
        assert!(
            stub.contains("page: int | None = None") || stub.contains("page: Optional[int] = None"),
            "got:\n{stub}"
        );
        assert!(
            stub.contains("clip: float | None = None")
                || stub.contains("clip: Optional[float] = None"),
            "got:\n{stub}"
        );
        assert!(stub.contains("*args"), "got:\n{stub}");
        assert!(
            !stub.contains("*args:"),
            "*args must have no type, got:\n{stub}"
        );
        assert!(stub.contains("**kwargs"), "got:\n{stub}");
        assert!(
            !stub.contains("**kwargs:"),
            "**kwargs must have no type, got:\n{stub}"
        );
    }

    /// A token in the signature with no matching Rust param is kept verbatim.
    /// This covers the positional-only sentinel `/` and future unknown tokens.
    #[test]
    fn merge_unknown_token_kept_verbatim() {
        let f = make_fn(
            "my_fn",
            Some("known=None, /"),
            vec![make_param("known", syn::parse_quote! { Option<i32> })],
            syn::parse_quote! { () },
        );
        let stub = stub_for(vec![PyItem::Function(f)]);
        assert!(
            stub.contains("known: int | None = None, /"),
            "positional-only '/' should be preserved with typed param, got:\n{stub}"
        );
    }

    /// Bare `*` (keyword-only separator) is emitted as-is without type annotation.
    /// `(a, *, b=None)` must not become `(a, *: Any, b: ...)`.
    #[test]
    fn merge_bare_star_keyword_only_separator() {
        let f = make_fn(
            "my_fn",
            Some("a, *, b=None"),
            vec![
                make_param("a", syn::parse_quote! { i32 }),
                make_param("b", syn::parse_quote! { Option<i32> }),
            ],
            syn::parse_quote! { () },
        );
        let stub = stub_for(vec![PyItem::Function(f)]);
        assert!(
            stub.contains("a: int, *, b: int | None = None"),
            "bare '*' should be kept as separator without type, got:\n{stub}"
        );
        assert!(
            !stub.contains("*:"),
            "bare '*' must not gain a type annotation, got:\n{stub}"
        );
    }

    /// `*args` gets the correct type from the Rust param (e.g. `Vec<i32>` → `list[int]`).
    /// `*args` is emitted without a type (unpacked positional args).
    #[test]
    fn merge_args_no_type() {
        let f = make_fn(
            "my_fn",
            Some("a, *args"),
            vec![
                make_param("a", syn::parse_quote! { i32 }),
                make_param("args", syn::parse_quote! { Vec<i32> }),
            ],
            syn::parse_quote! { () },
        );
        let stub = stub_for(vec![PyItem::Function(f)]);
        assert!(stub.contains("*args"), "got:\n{stub}");
        assert!(
            !stub.contains("*args:"),
            "*args should have no type annotation, got:\n{stub}"
        );
    }

    /// When no `signature_override` is set, `gen_params` is used unchanged (regression guard).
    #[test]
    fn no_signature_override_uses_rust_params_directly() {
        let f = make_fn(
            "add",
            None, // no override
            vec![
                make_param("a", syn::parse_quote! { i32 }),
                make_param("b", syn::parse_quote! { i32 }),
            ],
            syn::parse_quote! { i32 },
        );
        let stub = stub_for(vec![PyItem::Function(f)]);
        assert!(
            stub.contains("def add(a: int, b: int) -> int"),
            "got:\n{stub}"
        );
    }

    // ── RenderPolicy: python_version drives future_annotations, Self, Optional ─

    /// With python_version 3.9, stub must contain `from __future__ import annotations`
    /// and class method returning Self must show the class name (e.g. PdfDocument), not Self.
    #[test]
    fn render_policy_py39_emits_future_annotations_and_class_name_for_self() {
        let config = config_with_python_version("3.9");
        let class = make_class_with_self_return("PdfDocument", "from_bytes");
        let stub = stub_for_config(vec![PyItem::Class(class)], &config);
        assert!(
            stub.contains("from __future__ import annotations"),
            "py 3.9 must emit future annotations, got:\n{stub}"
        );
        assert!(
            stub.contains("-> PdfDocument:"),
            "py 3.9 must use class name as return type, got:\n{stub}"
        );
        assert!(
            stub.contains("data: bytes"),
            "from_bytes param must be bytes, got:\n{stub}"
        );
        assert!(
            !stub.contains("from typing import Self"),
            "py 3.9 should not import Self, got:\n{stub}"
        );
    }

    /// With python_version 3.12 (native_self), stub must NOT add future_annotations,
    /// must add `from typing import Self`, and return type must be Self.
    #[test]
    fn render_policy_py312_emits_native_self_and_no_future_annotations() {
        let config = config_with_python_version("3.12");
        let class = make_class_with_self_return("PdfDocument", "from_bytes");
        let stub = stub_for_config(vec![PyItem::Class(class)], &config);
        assert!(
            !stub.contains("from __future__ import annotations"),
            "py 3.12 with native Self should not emit future annotations, got:\n{stub}"
        );
        assert!(
            stub.contains("from typing import Self"),
            "py 3.12 must import Self when used, got:\n{stub}"
        );
        assert!(
            stub.contains("-> Self:") || stub.contains("-> Self :"),
            "py 3.12 must use Self as return type, got:\n{stub}"
        );
    }

    /// Option param with python_version 3.9 must use Optional[X] syntax.
    #[test]
    fn render_policy_py39_option_param_uses_optional_syntax() {
        let config = config_with_python_version("3.9");
        let f = make_fn(
            "foo",
            None,
            vec![make_param("x", syn::parse_quote! { Option<i32> })],
            syn::parse_quote! { () },
        );
        let stub = stub_for_config(vec![PyItem::Function(f)], &config);
        assert!(
            stub.contains("x: Optional[int]"),
            "py 3.9 must use Optional[int], got:\n{stub}"
        );
        assert!(stub.contains("from typing import Optional"), "got:\n{stub}");
    }

    /// Option param with python_version 3.10 must use X | None syntax (default config).
    #[test]
    fn render_policy_py310_option_param_uses_union_syntax() {
        let config = config_with_python_version("3.10");
        let f = make_fn(
            "foo",
            None,
            vec![make_param("x", syn::parse_quote! { Option<i32> })],
            syn::parse_quote! { () },
        );
        let stub = stub_for_config(vec![PyItem::Function(f)], &config);
        assert!(
            stub.contains("x: int | None"),
            "py 3.10 must use int | None, got:\n{stub}"
        );
    }

    // ── collect_class_names ──────────────────────────────────────────────────

    fn make_class(rust_name: &str, python_name: &str) -> PyClass {
        PyClass {
            name: python_name.to_string(),
            rust_name: rust_name.to_string(),
            module: None,
            doc: vec![],
            methods: vec![],
            source_file: dummy_path(),
        }
    }

    /// Classes at the top level and inside nested sub-modules are all collected.
    #[test]
    fn collect_class_names_recurses_into_nested_modules() {
        let inner_module = PyModule {
            name: "inner".to_string(),
            doc: vec![],
            items: vec![PyItem::Class(make_class("PyInner", "Inner"))],
            source_file: dummy_path(),
        };
        let outer_module = PyModule {
            name: "outer".to_string(),
            doc: vec![],
            items: vec![
                PyItem::Class(make_class("PyOuter", "Outer")),
                PyItem::Module(inner_module),
            ],
            source_file: dummy_path(),
        };

        let (map, warnings) = collect_class_names(&[outer_module]);

        assert_eq!(map.get("PyOuter").map(String::as_str), Some("Outer"));
        assert_eq!(map.get("PyInner").map(String::as_str), Some("Inner"));
        assert!(warnings.is_empty(), "no collision expected");
    }

    /// When two classes share the same Rust name, the first registration wins
    /// and a warning is emitted — no silent overwrite.
    #[test]
    fn collect_class_names_warns_on_rust_name_collision() {
        let mod_a = PyModule {
            name: "mod_a".to_string(),
            doc: vec![],
            items: vec![PyItem::Class(make_class("Shared", "PythonA"))],
            source_file: dummy_path(),
        };
        let mod_b = PyModule {
            name: "mod_b".to_string(),
            doc: vec![],
            items: vec![PyItem::Class(make_class("Shared", "PythonB"))],
            source_file: dummy_path(),
        };

        let (map, warnings) = collect_class_names(&[mod_a, mod_b]);

        assert_eq!(
            map.get("Shared").map(String::as_str),
            Some("PythonA"),
            "first registration must win"
        );
        assert_eq!(warnings.len(), 1, "exactly one collision warning expected");
        assert!(
            warnings[0].contains("Shared"),
            "warning must mention the colliding Rust name"
        );
    }

    // ── FallbackStrategy ─────────────────────────────────────────────────────

    fn make_fn_unknown_return(name: &str) -> PyFunction {
        make_fn(name, None, vec![], syn::parse_quote! { SomeOpaqueType })
    }

    /// With `fallback.strategy = "error"`, an unknown type must cause generation to fail.
    #[test]
    fn fallback_strategy_error_returns_err_on_unknown_type() {
        let mut config = Config::default();
        config.fallback.strategy = FallbackStrategy::Error;
        let f = make_fn_unknown_return("risky");
        let result = generate(&[make_module(vec![PyItem::Function(f)])], &config);
        assert!(
            result.is_err(),
            "expected Err for unknown type with Error strategy"
        );
        let msg = result.unwrap_err().to_string();
        assert!(
            msg.contains("unknown type"),
            "error message should mention unknown type, got: {msg}"
        );
    }

    /// With `fallback.strategy = "skip"`, an unknown type must not cause an error;
    /// the item is still emitted with `Any` (current behaviour: skip == silent Any).
    #[test]
    fn fallback_strategy_skip_succeeds_on_unknown_type() {
        let mut config = Config::default();
        config.fallback.strategy = FallbackStrategy::Skip;
        let f = make_fn_unknown_return("quiet");
        let stub = generate(&[make_module(vec![PyItem::Function(f)])], &config)
            .expect("Skip strategy must not return an error");
        assert!(
            stub.contains("def quiet"),
            "function should still be emitted, got:\n{stub}"
        );
    }

    // ── config.overrides ─────────────────────────────────────────────────────

    /// A manual override entry matching a function name must replace the generated stub line.
    #[test]
    fn config_override_replaces_generated_stub() {
        use crate::config::OverrideEntry;
        let mut config = Config::default();
        config.overrides.push(OverrideEntry {
            item: "complex_fn".to_string(),
            stub: "def complex_fn(x: Any, **kwargs: Any) -> dict[str, Any]: ...".to_string(),
        });
        let f = make_fn("complex_fn", None, vec![], syn::parse_quote! { () });
        let stub = stub_for_config(vec![PyItem::Function(f)], &config);
        assert!(
            stub.contains("def complex_fn(x: Any, **kwargs: Any) -> dict[str, Any]: ..."),
            "override stub should appear verbatim, got:\n{stub}"
        );
        assert!(
            !stub.contains("def complex_fn() ->"),
            "auto-generated version must not appear when overridden, got:\n{stub}"
        );
    }

    /// A fully-qualified override (`module::item`) must also match.
    #[test]
    fn config_override_qualified_path_matches() {
        use crate::config::OverrideEntry;
        let mut config = Config::default();
        config.overrides.push(OverrideEntry {
            item: "m::qualified_fn".to_string(),
            stub: "def qualified_fn() -> int: ...".to_string(),
        });
        let f = make_fn("qualified_fn", None, vec![], syn::parse_quote! { () });
        let stub = stub_for_config(vec![PyItem::Function(f)], &config);
        assert!(
            stub.contains("def qualified_fn() -> int: ..."),
            "qualified override must match, got:\n{stub}"
        );
    }

    // ── add_header ───────────────────────────────────────────────────────────

    #[test]
    fn add_header_true_prepends_comment() {
        let mut config = Config::default();
        config.output.add_header = true;
        let f = make_fn("foo", None, vec![], syn::parse_quote! { () });
        let stub = stub_for_config(vec![PyItem::Function(f)], &config);
        assert!(
            stub.starts_with("# Auto-generated"),
            "header should be first line, got:\n{stub}"
        );
    }

    // ── Module-level constant (m.add → Final[...]) ───────────────────────────

    #[test]
    fn constant_emits_final_annotation_and_typing_import() {
        let c = PyConstant {
            name: "__version__".to_string(),
            py_type: "str".to_string(),
        };
        let stub = stub_for(vec![PyItem::Constant(c)]);
        assert!(
            stub.contains("__version__: Final[str]"),
            "stub should contain Final[str] annotation, got:\n{stub}"
        );
        assert!(
            stub.contains("from typing import Final"),
            "stub should import Final when constant is present, got:\n{stub}"
        );
    }

    #[test]
    fn constant_with_other_typing_imports_includes_final() {
        let c = PyConstant {
            name: "VERSION".to_string(),
            py_type: "str".to_string(),
        };
        let f = make_fn("foo", None, vec![], syn::parse_quote! { () });
        let mut config = Config::default();
        config.output.python_version = "3.9".to_string();
        let stub = stub_for_config(vec![PyItem::Constant(c), PyItem::Function(f)], &config);
        assert!(stub.contains("VERSION: Final[str]"), "got:\n{stub}");
        assert!(
            stub.contains("Final") && stub.contains("from typing import"),
            "typing import line should include Final, got:\n{stub}"
        );
    }

    #[test]
    fn add_header_false_omits_comment() {
        let mut config = Config::default();
        config.output.add_header = false;
        let f = make_fn("foo", None, vec![], syn::parse_quote! { () });
        let stub = stub_for_config(vec![PyItem::Function(f)], &config);
        assert!(
            !stub.contains("# Auto-generated"),
            "header must be absent when add_header = false, got:\n{stub}"
        );
    }

    // ── gen_method: special MethodKinds ─────────────────────────────────────

    fn make_method(name: &str, kind: MethodKind, params: Vec<PyParam>, ret: syn::Type) -> PyMethod {
        PyMethod {
            name: name.to_string(),
            doc: vec![],
            kind,
            signature_override: None,
            params,
            return_type: PyType {
                rust_type: ret,
                override_str: None,
            },
        }
    }

    fn make_class_with_methods(class_name: &str, methods: Vec<PyMethod>) -> PyClass {
        PyClass {
            name: class_name.to_string(),
            rust_name: class_name.to_string(),
            module: None,
            doc: vec![],
            methods,
            source_file: dummy_path(),
        }
    }

    #[test]
    fn new_method_generates_init() {
        let m = make_method(
            "new",
            MethodKind::New,
            vec![make_param("x", syn::parse_quote! { i32 })],
            syn::parse_quote! { () },
        );
        let class = make_class_with_methods("Counter", vec![m]);
        let stub = stub_for(vec![PyItem::Class(class)]);
        assert!(
            stub.contains("def __init__(self, x: int) -> None:"),
            "#[new] must emit __init__, got:\n{stub}"
        );
    }

    #[test]
    fn new_method_with_signature_override_emits_kwargs() {
        // #[new] with #[pyo3(signature = (**kwargs))] — **kwargs are unpacked, so type is Any not dict.
        let mut m = make_method(
            "new",
            MethodKind::New,
            vec![make_param(
                "kwargs",
                syn::parse_quote! { Option<&pyo3::Bound<'_, pyo3::types::PyDict>> },
            )],
            syn::parse_quote! { () },
        );
        m.signature_override = Some("**kwargs".to_string());
        let class = make_class_with_methods("TfSettings", vec![m]);
        let stub = stub_for(vec![PyItem::Class(class)]);
        assert!(
            stub.contains("def __init__(self, **kwargs) -> None:"),
            "#[new] with signature (**kwargs) must emit __init__(self, **kwargs), got:\n{stub}"
        );
    }

    #[test]
    fn getter_method_generates_property() {
        let m = make_method(
            "value",
            MethodKind::Getter("value".to_string()),
            vec![],
            syn::parse_quote! { i32 },
        );
        let class = make_class_with_methods("Counter", vec![m]);
        let stub = stub_for(vec![PyItem::Class(class)]);
        assert!(
            stub.contains("@property"),
            "getter must emit @property, got:\n{stub}"
        );
        assert!(
            stub.contains("def value(self) -> int:"),
            "getter must emit def value(self), got:\n{stub}"
        );
    }

    #[test]
    fn getter_with_rename_uses_property_name() {
        let m = make_method(
            "get_count",
            MethodKind::Getter("count".to_string()),
            vec![],
            syn::parse_quote! { i32 },
        );
        let class = make_class_with_methods("Counter", vec![m]);
        let stub = stub_for(vec![PyItem::Class(class)]);
        assert!(
            stub.contains("def count(self) -> int:"),
            "renamed getter must use property name, got:\n{stub}"
        );
    }

    #[test]
    fn setter_method_generates_setter_decorator() {
        let m = make_method(
            "set_value",
            MethodKind::Setter("value".to_string()),
            vec![make_param("v", syn::parse_quote! { i32 })],
            syn::parse_quote! { () },
        );
        let class = make_class_with_methods("Counter", vec![m]);
        let stub = stub_for(vec![PyItem::Class(class)]);
        assert!(
            stub.contains("@value.setter"),
            "setter must emit @value.setter, got:\n{stub}"
        );
        assert!(
            stub.contains("def value(self, value: int) -> None:"),
            "setter must emit def value(self, value: T), got:\n{stub}"
        );
    }

    #[test]
    fn classmethod_generates_classmethod_decorator() {
        let m = make_method(
            "create",
            MethodKind::Class,
            vec![],
            syn::parse_quote! { Self },
        );
        let class = make_class_with_methods("MyClass", vec![m]);
        let stub = stub_for(vec![PyItem::Class(class)]);
        assert!(
            stub.contains("@classmethod"),
            "@classmethod decorator must appear, got:\n{stub}"
        );
        assert!(
            stub.contains("def create(self)"),
            "classmethod must include self param, got:\n{stub}"
        );
    }

    // ── gen_module: nested submodule ─────────────────────────────────────────

    #[test]
    fn nested_submodule_generates_class_namespace() {
        let inner = PyModule {
            name: "utils".to_string(),
            doc: vec![],
            items: vec![PyItem::Function(make_fn(
                "helper",
                None,
                vec![],
                syn::parse_quote! { i32 },
            ))],
            source_file: dummy_path(),
        };
        let stub = stub_for(vec![PyItem::Module(inner)]);
        assert!(
            stub.contains("class utils:"),
            "submodule must be emitted as class, got:\n{stub}"
        );
        // Functions inside a sub-namespace module are emitted as regular `def` (no `self`).
        assert!(
            stub.contains("def helper() -> int:"),
            "inner function must appear inside namespace, got:\n{stub}"
        );
    }

    // ── gen_docstring ─────────────────────────────────────────────────────────

    #[test]
    fn single_line_docstring_inline_triple_quotes() {
        let mut f = make_fn("described", None, vec![], syn::parse_quote! { () });
        f.doc = vec!["A brief description.".to_string()];
        let stub = stub_for(vec![PyItem::Function(f)]);
        assert!(
            stub.contains("\"\"\"A brief description.\"\"\""),
            "single-line doc must use inline triple quotes, got:\n{stub}"
        );
    }

    #[test]
    fn multi_line_docstring_uses_block_format() {
        let mut f = make_fn("described", None, vec![], syn::parse_quote! { () });
        f.doc = vec!["First line.".to_string(), "Second line.".to_string()];
        let stub = stub_for(vec![PyItem::Function(f)]);
        assert!(
            stub.contains("\"\"\""),
            "multi-line doc must start with triple quotes, got:\n{stub}"
        );
        assert!(
            stub.contains("First line."),
            "first doc line must appear, got:\n{stub}"
        );
        assert!(
            stub.contains("Second line."),
            "second doc line must appear, got:\n{stub}"
        );
        assert!(
            !stub.contains("\"\"\"First line.\"\"\""),
            "multi-line must not use inline format, got:\n{stub}"
        );
    }
}
