use crate::collector::{
    MethodKind, ParamKind, PyClass, PyFunction, PyItem, PyMethod, PyModule, PyParam, PyType,
};
use crate::config::{Config, FallbackStrategy};
use crate::type_map::{self, TypeMapping};
use anyhow::{Result, bail};

// ── Public entry point ───────────────────────────────────────────────────────

pub fn generate(modules: &[PyModule], config: &Config) -> Result<String> {
    let mut ctx = GenCtx {
        config,
        needs_any: false,
        needs_optional: false,
        warnings: Vec::new(),
    };

    let mut body = String::new();
    for module in modules {
        ctx.gen_module(module, &mut body, 0)?;
    }

    let mut out = String::new();

    // Header
    if config.output.add_header {
        out.push_str("# Auto-generated by rylai. Do not edit manually.\n\n");
    }

    // Imports
    if ctx.needs_any || ctx.needs_optional {
        out.push_str("from typing import");
        let mut parts = Vec::new();
        if ctx.needs_any {
            parts.push("Any");
        }
        if ctx.needs_optional {
            parts.push("Optional");
        }
        out.push_str(&format!(" {}\n\n", parts.join(", ")));
    }

    out.push_str(&body);

    // Print warnings to stderr
    for w in &ctx.warnings {
        eprintln!("warning: {w}");
    }

    Ok(out)
}

// ── Generation context ───────────────────────────────────────────────────────

struct GenCtx<'a> {
    config: &'a Config,
    needs_any: bool,
    needs_optional: bool,
    warnings: Vec<String>,
}

impl<'a> GenCtx<'a> {
    fn resolve_type(&mut self, py_type: &PyType, location: &str) -> Result<String> {
        // User override takes priority
        if let Some(ov) = &py_type.override_str {
            return Ok(ov.clone());
        }

        let mapping = type_map::map_type(&py_type.rust_type, self.config.use_union_syntax());
        self.absorb_mapping(&mapping, location)?;
        Ok(mapping.py_type)
    }

    fn absorb_mapping(&mut self, m: &TypeMapping, location: &str) -> Result<()> {
        if m.needs_any {
            self.needs_any = true;
        }
        if m.needs_optional {
            self.needs_optional = true;
        }
        if m.is_unknown {
            match self.config.fallback.strategy {
                FallbackStrategy::Any => {
                    self.warnings.push(format!(
                        "unknown type at `{location}` — falling back to `Any`"
                    ));
                }
                FallbackStrategy::Error => {
                    bail!("unknown type at `{location}` and fallback strategy is `error`");
                }
                FallbackStrategy::Skip => {
                    // Caller checks is_unknown and skips the item
                }
            }
        }
        Ok(())
    }

    // ── Module ───────────────────────────────────────────────────────────────

    fn gen_module(&mut self, module: &PyModule, out: &mut String, indent: usize) -> Result<()> {
        let pad = "    ".repeat(indent);

        if !module.doc.is_empty() {
            out.push_str(&format!("{pad}# Module: {}\n", module.name));
        }

        for item in &module.items {
            // Check for manual override
            let override_stub = self.config.overrides.iter().find(|o| {
                o.item.ends_with(&format!("::{}", item_name(item))) || o.item == item_name(item)
            });
            if let Some(ov) = override_stub {
                out.push_str(&format!("{pad}{}\n\n", ov.stub));
                continue;
            }

            match item {
                PyItem::Function(f) => self.gen_function(f, out, indent)?,
                PyItem::Class(c) => self.gen_class(c, out, indent)?,
                PyItem::Module(m) => {
                    // Submodule: emit a class stub as a namespace approximation
                    out.push_str(&format!("{pad}class {}:\n", m.name));
                    if !m.doc.is_empty() {
                        self.gen_docstring(&m.doc, out, indent + 1);
                    }
                    self.gen_module(m, out, indent + 1)?;
                    out.push('\n');
                }
            }
        }
        Ok(())
    }

    // ── Function ─────────────────────────────────────────────────────────────

    fn gen_function(&mut self, f: &PyFunction, out: &mut String, indent: usize) -> Result<()> {
        let pad = "    ".repeat(indent);
        let ret = self.resolve_type(&f.return_type, &format!("{}::return", f.name))?;

        let params_str = if let Some(sig) = &f.signature_override {
            // #[pyo3(signature = (...))] — inner content only, no surrounding parens
            sig.clone()
        } else {
            self.gen_params(&f.params, &f.name, false)?
        };

        out.push_str(&format!("{pad}def {}({params_str}) -> {ret}:\n", f.name));

        if !f.doc.is_empty() {
            self.gen_docstring(&f.doc, out, indent + 1);
        } else {
            out.push_str(&format!("{pad}    ...\n"));
        }
        out.push('\n');
        Ok(())
    }

    // ── Class ────────────────────────────────────────────────────────────────

    fn gen_class(&mut self, c: &PyClass, out: &mut String, indent: usize) -> Result<()> {
        let pad = "    ".repeat(indent);
        out.push_str(&format!("{pad}class {}:\n", c.name));

        if !c.doc.is_empty() {
            self.gen_docstring(&c.doc, out, indent + 1);
        }

        if c.methods.is_empty() {
            out.push_str(&format!("{pad}    ...\n"));
        } else {
            for method in &c.methods {
                self.gen_method(method, &c.name, out, indent + 1)?;
            }
        }
        out.push('\n');
        Ok(())
    }

    fn gen_method(
        &mut self,
        m: &PyMethod,
        class_name: &str,
        out: &mut String,
        indent: usize,
    ) -> Result<()> {
        let pad = "    ".repeat(indent);
        let location = format!("{}::{}", class_name, m.name);
        let ret = self.resolve_type(&m.return_type, &format!("{location}::return"))?;

        match &m.kind {
            MethodKind::New => {
                let params = self.gen_params(&m.params, &location, true)?;
                out.push_str(&format!("{pad}def __init__({params}) -> None:\n"));
            }
            MethodKind::Static => {
                out.push_str(&format!("{pad}@staticmethod\n"));
                let params = self.gen_params(&m.params, &location, false)?;
                out.push_str(&format!("{pad}def {}({params}) -> {ret}:\n", m.name));
            }
            MethodKind::Class => {
                out.push_str(&format!("{pad}@classmethod\n"));
                let params = self.gen_params(&m.params, &location, true)?;
                out.push_str(&format!("{pad}def {}({params}) -> {ret}:\n", m.name));
            }
            MethodKind::Getter(prop) => {
                out.push_str(&format!("{pad}@property\n"));
                out.push_str(&format!("{pad}def {prop}(self) -> {ret}:\n"));
            }
            MethodKind::Setter(prop) => {
                // setter takes one value param
                let val_type = m
                    .params
                    .first()
                    .map(|p| self.resolve_type(&p.ty, &location))
                    .transpose()?
                    .unwrap_or_else(|| "Any".to_string());
                if val_type == "Any" {
                    self.needs_any = true;
                }
                out.push_str(&format!("{pad}@{prop}.setter\n"));
                out.push_str(&format!(
                    "{pad}def {prop}(self, value: {val_type}) -> None:\n"
                ));
            }
            MethodKind::Instance => {
                let params = self.gen_params(&m.params, &location, true)?;
                out.push_str(&format!("{pad}def {}({params}) -> {ret}:\n", m.name));
            }
        }

        if !m.doc.is_empty() {
            self.gen_docstring(&m.doc, out, indent + 1);
        } else {
            out.push_str(&format!("{pad}    ...\n"));
        }
        out.push('\n');
        Ok(())
    }

    // ── Params ───────────────────────────────────────────────────────────────

    fn gen_params(
        &mut self,
        params: &[PyParam],
        location: &str,
        with_self: bool,
    ) -> Result<String> {
        let mut parts: Vec<String> = Vec::new();
        if with_self {
            parts.push("self".to_string());
        }
        for p in params {
            let ty = self.resolve_type(&p.ty, &format!("{location}::{}", p.name))?;
            let part = match p.kind {
                ParamKind::Args => format!("*{}: {ty}", p.name),
                ParamKind::Kwargs => format!("**{}: {ty}", p.name),
                ParamKind::Regular => {
                    if let Some(default) = &p.default {
                        format!("{}: {} = {}", p.name, ty, default)
                    } else {
                        format!("{}: {ty}", p.name)
                    }
                }
            };
            parts.push(part);
        }
        Ok(parts.join(", "))
    }

    // ── Docstring ────────────────────────────────────────────────────────────

    fn gen_docstring(&self, lines: &[String], out: &mut String, indent: usize) {
        let pad = "    ".repeat(indent);
        if lines.len() == 1 {
            out.push_str(&format!("{pad}\"\"\"{}\"\"\"\n", lines[0]));
        } else {
            out.push_str(&format!("{pad}\"\"\"\n"));
            for line in lines {
                out.push_str(&format!("{pad}{line}\n"));
            }
            out.push_str(&format!("{pad}\"\"\"\n"));
        }
    }
}

// ── Helpers ──────────────────────────────────────────────────────────────────

fn item_name(item: &PyItem) -> &str {
    match item {
        PyItem::Function(f) => &f.name,
        PyItem::Class(c) => &c.name,
        PyItem::Module(m) => &m.name,
    }
}
