//! Literal strings written into generated `.pyi` files. Used by [`crate::generator`] and
//! [`crate::add_content`] so wording stays in one place.

/// Header comment plus the following blank line when [`crate::config::OutputConfig::add_header`] is true.
pub const AUTO_GENERATED_BANNER: &str = "# Auto-generated by rylai. Do not edit manually.\n\n";

/// The single `import typing as t` line (no trailing newline). The generator emits this followed by `\n\n`.
pub const TYPING_IMPORT_LINE: &str = "import typing as t";
