# Auto-generated by rylai. Do not edit manually.

from __future__ import annotations

import typing as t

__all__ = [
    "Foo",
    "Bar",
    "add",
    "Baz",
    "Qux",
]

# Module: macro_expand_sample
@t.final
class Foo:
    def __init__(self) -> None: ...
    def foo(self) -> str: ...

@t.final
class Bar:
    def __init__(self) -> None: ...
    def bar(self) -> str: ...

def add(a: int, b: int) -> int:
    """A simple function so the module has a callable too."""

@t.final
class Baz:
    def __init__(self) -> None: ...
    def baz(self) -> str: ...

@t.final
class Qux:
    def __init__(self) -> None: ...
    def qux(self) -> str: ...
